In [1]:
import numpy as np

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.array([1,2,3], "complex") # For complex number representation

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
print(arr[1:6:2]) # This systax of slice -- [start         :        end           :  step]
                                            # start_from , end_step_one_step_ahead, step of gap
print(arr[:3])

# MULTI SLICE
arr1 = np.array(
    [
        [0,1,2,3,4,5], 
        [6,7,8,9,10,11]
    ]
    )

print("Ex of slice 2D - ",arr1[:3 , 2:5]) #This 2nd half refers where to slice even if we declear in first half to slice from 0 to 2
print("More ex - ",arr1[0:2, 0:2])
#                      row , col 

[2 4 6]
[1 2 3]
Ex of slice 2D -  [[ 2  3  4]
 [ 8  9 10]]
More ex -  [[0 1]
 [6 7]]


In [15]:

# =-------ARANGE ------==
# syntax - arrange( start, stop ,)
ab = np.arange(10) #kinda like range()
# print(ab)

# syntax - arrange(start, stop, step)
# means starts from and stoped at. and the step between them is the last one

d1 = np.arange(10, dtype="complex")
# ^---> for this the syntax : arange(stop, dtype)

d2 = np.arange(1, 12, 2 , dtype="float")
# ^--> for this arange(start, stop, step, dtype)

print(d1)
print(d2)


[0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]
[ 1.  3.  5.  7.  9. 11.]


In [27]:
d6 = np.zeros(4, order="F")
print(d6)
print("2D zeros ==> ")
d7 = np.zeros(shape=[2,3],dtype="int")
print(d7)

[0. 0. 0. 0.]
2D zeros ==> 
[[0 0 0]
 [0 0 0]]


In [29]:
# BROADCASTING -->>
a = np.array([1, 2, 3])
result = a + 10 
result

array([11, 12, 13])

In [32]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
b1 = np.array([10, 20, 30])
result1 = a1 + b1
result1

array([[11, 22, 33],
       [14, 25, 36]])

In [34]:
d = np.array([1, 2, 3])
e = np.array([10, 20,5,7])
result2 = d[:, np.newaxis] + e
result2

array([[11, 21,  6,  8],
       [12, 22,  7,  9],
       [13, 23,  8, 10]])